Api::V1::Team.create(name: "Atlanta Hawks")
Api::V1::Team.create(name: "Boston Celtics")
Api::V1::Team.create(name: "Brooklyn Nets")
Api::V1::Team.create(name: "Charlotte Hornets")
Api::V1::Team.create(name: "Chicago Bulls")
Api::V1::Team.create(name: "Cleveland Cavaliers")
Api::V1::Team.create(name: "Dallas Mavericks")
Api::V1::Team.create(name: "Denver Nuggets")
Api::V1::Team.create(name: "Detroit Pistons")
Api::V1::Team.create(name: "Golden State Warriors")
Api::V1::Team.create(name: "Houston Rockets")
Api::V1::Team.create(name: "Indiana Pacers")
Api::V1::Team.create(name: "Los Angeles Clippers")
Api::V1::Team.create(name: "Los Angeles Lakers")
Api::V1::Team.create(name: "Memphis Grizzlies")
Api::V1::Team.create(name: "Miami Heat")
Api::V1::Team.create(name: "Milwakee Bucks")
Api::V1::Team.create(name: "Minnesota Timberwolves")
Api::V1::Team.create(name: "New Orleans Hornets")
Api::V1::Team.create(name: "New York Knicks")
Api::V1::Team.create(name: "Oklahoma City Thunder")
Api::V1::Team.create(name: "Orlando Magic")
Api::V1::Team.create(name: "Philadelphia 76ers")
Api::V1::Team.create(name: "Phoenix Suns")
Api::V1::Team.create(name: "Portland Trail Blazers")
Api::V1::Team.create(name: "Sacramento Kings")
Api::V1::Team.create(name: "San Antonio Spurs")
Api::V1::Team.create(name: "Toronto Raptors")
Api::V1::Team.create(name: "Utah Jazz")
Api::V1::Team.create(name: "Washington Wizards")
